# android studio
export ANDROID_HOME="/home/jacob/Android/Sdk/"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/tools"
alias Nexus-5="emulator -avd Nexus_5x_1 -no-snapshot 1> /dev/null &"
alias rnra="react-native run-android"
alias rnresetcache="watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && npm install && npm start -- --reset-cache"

if [[ "$(uname 2> /dev/null)" == "Linux" ]]; then
  export ZSH=/home/jacob/.oh-my-zsh
fi

if [[ "$(uname 2> /dev/null)" == "Darwin" ]]; then
  export ZSH=/Users/jacob/.oh-my-zsh
fi

if [[ "$(uname 2> /dev/null)" == "Linux" ]]; then
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
fi

alias resauce="source ~/.zshrc"
alias stop_that_right_now='shutdown now'

markdown () {
  pandoc $1 | lynx -stdin
}

line_count () {
  find $1 -type f -exec cat {} + | wc -l
}

# git stuff
alias groot='"$(git rev-parse --show-toplevel)"'
alias gcd='cd "$(git rev-parse --show-toplevel)"'
alias gbpurge='git branch --merged | grep -v "\*" | grep -v "master" | grep -v "develop" | grep -v "staging" | xargs -n 1 git branch -d' 
gitprune () {
    git fetch -p
    for branch in `git branch -vv | grep ': gone]' | awk '{print $1}'`
    do
        git branch -D $branch
    done
}
alias justmaster='git branch | grep -v "master" | xargs git branch -D'

export EDITOR=nvim 
export GIT_EDITOR=nvim 
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""' 
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND" 
alias sudo='sudo ' 
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  

alias vim='nvim'
viag () { vim -c "Ack $*" }
ZSH_THEME=amuse

source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/google-cloud-sdk-226.0.0-linux-x86_64/google-cloud-sdk/path.zsh.inc' ]; then . '/usr/local/google-cloud-sdk-226.0.0-linux-x86_64/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/google-cloud-sdk-226.0.0-linux-x86_64/google-cloud-sdk/completion.zsh.inc' ]; then . '/usr/local/google-cloud-sdk-226.0.0-linux-x86_64/google-cloud-sdk/completion.zsh.inc'; fi

# usql
# alias db-prod='usql mysql://mishguru@localhost:19530/mishguruproduction'
# alias db-prod-meta='usql mysql://mishguru@localhost:19531/mishmetaproduction'
# alias db-internal='usql mysql://mishguru@localhost:19532/mishguruinternal'
# alias db-internal-meta='usql mysql://mishguru@localhost:19532/mishmetainternal'

# mycli
alias prod-pass='cat ~/.mish_production | grep SQL_PASS | cut -d= -f2 | sed "s/'\''//g" | xclip -i -selection clipboard'
alias db-prod='mycli --login-path=db-prod mishguruproduction'
alias db-prod-meta='mycli --login-path=db-prod-meta mishgurumeta'
alias db-internal='mycli --login-path=db-internal mishguruinternal'
alias db-internal-meta='mysql --login-path=db-internal-meta mishmetainternal'
# other
xmodmap -e "keycode 94 = Shift_L"


