if [[ "$(uname 2> /dev/null)" == "Linux" ]]; then
  export ZSH=/home/jacob/.oh-my-zsh
fi

if [[ "$(uname 2> /dev/null)" == "Darwin" ]]; then
  export ZSH=/Users/jacob/.oh-my-zsh
fi

alias groot='"$(git rev-parse --show-toplevel)"'
alias gcd='cd "$(git rev-parse --show-toplevel)"'
alias update-dependencies-and-push="git checkout master && \
git pull --rebase && \
ncu -a && \
npm install && \
git checkout -b dependency-update && \
git commit -a -m 'Update dependencies' && \
npm version minor && \
git push -u origin HEAD && \
hub pull-request -m 'Update dependencies'"

export EDITOR=nvim 
export GIT_EDITOR=nvim 
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""' 
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND" alias sudo='sudo ' 
alias gbpurge='git branch --merged | grep -v "\*" | grep -v "master" | grep -v "develop" | grep -v "staging" | xargs -n 1 git branch -d' 
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  

alias vim='nvim'
viag () { vim -c "Ag $*" }
ZSH_THEME=amuse

source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pb copy and paste for ubuntu
if [ "$(uname 2> /dev/null)" == "Linux" ]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

