export ZSH=/home/jacob/.oh-my-zsh
alias groot='"$(git rev-parse --show-toplevel)"'
alias gcd='cd "$(git rev-parse --show-toplevel)"'
export EDITOR=nvim 
export GIT_EDITOR=nvim 
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""' 
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND" alias sudo='sudo ' 
alias gbpurge='git branch --merged | grep -v "\*" | grep -v "master" | grep -v "develop" | grep -v "staging" | xargs -n 1 git branch -d' 
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  

alias vim='nvim'
ZSH_THEME=amuse

source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pb copy and paste for ubuntu
if [ "$(uname 2> /dev/null)" == "Linux" ]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

